print('===== Desafio 4 =====')

x = input('Digite algo: ')
print('O tipo primitivo de {} é {}'.format(x, type(x)))
print('Só tem espaços? {}'.format(x.isspace()))
print('É um número? {}'.format(x.isnumeric()))
print('É alfabético? {}'.format(x.isalpha()))
print('É alfanumérico? {}'.format(x.isalnum()))
print('Está em maiúsculas? {}'.format(x.isupper()))
print('Está em minúsculas? {}'.format(x.islower()))
print('Está capitalizada? {}'.format(x.istitle()))
print('Ele é imprimível? {}'.format(x.isprintable()))
print('Ele é um dígito? {}'.format(x.isdigit()))
